// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  commandText: __t.string().name("command_text"),
  intentJson: __t.string().name("intent_json"),
  assignedPcId: __t.option(__t.u64()).name("assigned_pc_id"),
  status: __t.string(),
  priority: __t.u32(),
  dependsOn: __t.option(__t.u64()).name("depends_on"),
  createdAt: __t.timestamp().name("created_at"),
});
