// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CommandSession = __t.object("CommandSession", {
  id: __t.u64(),
  rawInput: __t.string(),
  decomposedIntents: __t.string(),
  synthesisSummary: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type CommandSession = __Infer<typeof CommandSession>;

export const EnforcementLog = __t.object("EnforcementLog", {
  id: __t.u64(),
  taskId: __t.u64(),
  pcId: __t.u64(),
  actionType: __t.string(),
  decision: __t.string(),
  reason: __t.string(),
  timestamp: __t.timestamp(),
});
export type EnforcementLog = __Infer<typeof EnforcementLog>;

export const PcAgent = __t.object("PcAgent", {
  id: __t.u64(),
  hostname: __t.string(),
  ip: __t.string(),
  status: __t.string(),
  cpuLoad: __t.f32(),
  memoryUsage: __t.f32(),
  installedApps: __t.string(),
  lastHeartbeat: __t.timestamp(),
});
export type PcAgent = __Infer<typeof PcAgent>;

export const TaskQueue = __t.object("TaskQueue", {
  id: __t.u64(),
  commandText: __t.string(),
  intentJson: __t.string(),
  assignedPcId: __t.option(__t.u64()),
  status: __t.string(),
  priority: __t.u32(),
  dependsOn: __t.option(__t.u64()),
  createdAt: __t.timestamp(),
});
export type TaskQueue = __Infer<typeof TaskQueue>;

export const TaskResult = __t.object("TaskResult", {
  id: __t.u64(),
  taskId: __t.u64(),
  pcId: __t.u64(),
  stdout: __t.string(),
  stderr: __t.string(),
  exitCode: __t.i32(),
  fileDiffs: __t.string(),
  enforcementDecision: __t.string(),
  verificationToken: __t.string(),
  completedAt: __t.timestamp(),
});
export type TaskResult = __Infer<typeof TaskResult>;

