// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AssignTaskReducer from "../assign_task_reducer";
import LogEnforcementReducer from "../log_enforcement_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import ReportResultReducer from "../report_result_reducer";
import SendHeartbeatReducer from "../send_heartbeat_reducer";
import SubmitCommandReducer from "../submit_command_reducer";
import UpdateTaskStatusReducer from "../update_task_status_reducer";

export type AssignTaskParams = __Infer<typeof AssignTaskReducer>;
export type LogEnforcementParams = __Infer<typeof LogEnforcementReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type ReportResultParams = __Infer<typeof ReportResultReducer>;
export type SendHeartbeatParams = __Infer<typeof SendHeartbeatReducer>;
export type SubmitCommandParams = __Infer<typeof SubmitCommandReducer>;
export type UpdateTaskStatusParams = __Infer<typeof UpdateTaskStatusReducer>;

